### PR TITLE
Added files

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/swift56_amplicons/1)

### CODE REVIEW

**Comment by aledj2** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[gene_transcript_library.py, line 46 at r1](https://beta.reviewable.io/reviews/moka-guys/swift56_amplicons/1#-L3hWCF35b7YOXrHRwuw:-L3hWCF43rJ5CIvT0THT:b-dwduq4) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/cde685d4fa58ab619759cbe31d33f77030d4fe58/gene_transcript_library.py#L46)):*
> ```Python
> 			t_dict['exonFrames'] = map(int, t_dict['exonFrames'].rstrip(',').split(',')) #Convert comma separated string to list of numbers
> 			gene = t_dict['name2']
> 			self.gene_transcript_dict[gene]['transcripts'][t_dict['name']] = t_dict			
> ```

why is this name and not name2? (I think name==name2)

---

*[gene_transcript_library.py, line 60 at r1](https://beta.reviewable.io/reviews/moka-guys/swift56_amplicons/1#-L3hY-lI6_fhoOYnJMez:-L3hY-lI6_fhoOYnJMf-:b-swd0zw) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/cde685d4fa58ab619759cbe31d33f77030d4fe58/gene_transcript_library.py#L60)):*
> ```Python
> 					#Exons lying completely outside cds will not meet any of the following conditions so will be skipped
> 					#if coding sequence starts within the exon, change start site to cds start site
> 					if exon_start <= cds_start and exon_end >= cds_start:
> ```

what if exon_start <cds_start and exon_end > cds_end?

---

*[gene_transcript_library.py, line 98 at r1](https://beta.reviewable.io/reviews/moka-guys/swift56_amplicons/1#-L3haWkd-F22tK72szn1:-L3haWkd-F22tK72szn2:b-z52dmq) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/cde685d4fa58ab619759cbe31d33f77030d4fe58/gene_transcript_library.py#L98)):*
> def get_canonical(self):
> 		# Retrieve the canonical transcript for each gene from UCSC
> 		self.connect_db()
> 		canonical_transcripts = self.connection.execute("SELECT kgXref.geneSymbol, kgXref.refseq FROM knownCanonical JOIN kgXref ON knownCanonical.transcript = kgXref.kgID WHERE kgXref.geneSymbol IN ('" + "','".join(self.gene_transcript_dict.keys()) + "');")		
> 		self.disconnect_db()
> 		for tx in canonical_transcripts:
> 			self.gene_transcript_dict[tx['geneSymbol']]['canonical'] = tx['refseq']
not used?

---

*[gene_transcript_library.py, line 127 at r1](https://beta.reviewable.io/reviews/moka-guys/swift56_amplicons/1#-L3hWs98BFwHVVD2E0fk:-L3hWs992hBWhyOZjr6P:b-eo2shn) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/cde685d4fa58ab619759cbe31d33f77030d4fe58/gene_transcript_library.py#L127)):*
> ```Python
> 					transcripts[transcript] = transcripts.setdefault(transcript, 0) + 1 #Increase count by 1
> 			# Find transcript with the highest count
> 			counts_transcripts = [(count, tx) for tx, count in transcripts.items()]
> ```

max on a list of tuples works on the first element.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/moka-guys/swift56_amplicons/1)*

**Comment by andyb3** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[gene_transcript_library.py, line 46 at r1](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L3hWCF35b7YOXrHRwuw:-L3lfHS1iL4WcC3LVFrh:b3wem69) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/cde685d4fa58ab619759cbe31d33f77030d4fe58/gene_transcript_library.py#L46)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

why is this name and not name2? (I think name==name2)
</blockquote></details>

name is the transcript name (NM...), name2 is the gene name (great field naming from UCSC there!) . Have added this into comments

---

*[gene_transcript_library.py, line 60 at r1](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L3hY-lI6_fhoOYnJMez:-L3lf_aQonInEGZggNZ4:bwhx4jz) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/cde685d4fa58ab619759cbe31d33f77030d4fe58/gene_transcript_library.py#L60)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what if exon_start <cds_start and exon_end > cds_end?
</blockquote></details>

Good point!! Have added in a clause for that.

---

*[gene_transcript_library.py, line 98 at r1](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L3haWkd-F22tK72szn1:-L3lfhR_Axy_vWFXYwcG:b-kmpr71) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/cde685d4fa58ab619759cbe31d33f77030d4fe58/gene_transcript_library.py#L98)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> def get_canonical(self):
> 		# Retrieve the canonical transcript for each gene from UCSC
> 		self.connect_db()
> 		canonical_transcripts = self.connection.execute("SELECT kgXref.geneSymbol, kgXref.refseq FROM knownCanonical JOIN kgXref ON knownCanonical.transcript = kgXref.kgID WHERE kgXref.geneSymbol IN ('" + "','".join(self.gene_transcript_dict.keys()) + "');")		
> 		self.disconnect_db()
> 		for tx in canonical_transcripts:
> 			self.gene_transcript_dict[tx['geneSymbol']]['canonical'] = tx['refseq']
not used?
</blockquote></details>

No not used for the main output. I only used this method when producing a list of canonical and list of clinvar transcripts for Oncology so they could decided which transcripts they wanted.

---

*[gene_transcript_library.py, line 127 at r1](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L3hWs98BFwHVVD2E0fk:-L3lgUm63wdI02WxT9OU:b-uy1dri) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/cde685d4fa58ab619759cbe31d33f77030d4fe58/gene_transcript_library.py#L127)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

max on a list of tuples works on the first element.
</blockquote></details>

Have made this clear in comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1)*

**Comment by andyb3** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[SWIFT56_output.txt, line 28 at r1](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L3ljXNuVsJ3N_nbznQB:-L3ljXNuVsJ3N_nbznQC:b-le8rzv) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/cde685d4fa58ab619759cbe31d33f77030d4fe58/SWIFT56_output.txt#L28)):*
> ```
> 025_MLH1_V384D_F2	chr3	37067191	37067256	MLH1	NM_000249	+	1102	0	1167	0	368	368	389	389
> 026_CTNNB1_D32-S45_F2	chr3	41266037	41266140	CTNNB1	NM_001904	+	34	0	137	0	12	12	46	45
> 027_FOXL2_C134_R1	chr3	138665150	138665247	FOXL2	NM_023067	-	736	0	833	0	246	246	278	277
> ```

This gene only has 1 exon, and the amplicon starts and ends in UTR, so good that you spotted the missing 'if <cds_start and exon_end > cds_end' clause!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1)*

**Comment by aledj2** [comment]
Reviewed 1 of 5 files at r1, 2 of 3 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[gene_transcript_library.py, line 371 at r2](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L40nBD-fS3ZXk3_c9RW:-L40nBD-fS3ZXk3_c9RX:bd4qhpw) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/8cd66f3b86a1b8896eab249610c3455b35cd6493/gene_transcript_library.py#L371)):*
> ```Python
> 		aa_starts_in = int(math.floor((amp_cDNA_start+2)/3.0)) #math.floor round down
> 
> 		#If amp_cDNA_end is still None after the first step, loop through exons and find cDNA end position
> ```

if? I can't see this being assigned anywhere

---

*[gene_transcript_library.py, line 401 at r2](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L40on1TdLnnkDyERcZZ:-L40on1TdLnnkDyERcZ_:bzic6ye) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/8cd66f3b86a1b8896eab249610c3455b35cd6493/gene_transcript_library.py#L401)):*
> ```Python
> 		# e.g if the transcript ended at cDNA position 10 (so partway through codon 4). Would / 3 (= 3.3).
> 		# Round 3.3 down to get the last full codon included in the amplicon (3)
> 		# Round 3.3 up to get the codon that the amplicon actually ends in (2)
> ```

minor issue - this should be (3)

---

*[README.md, line 16 at r2](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L40oxplPhTnFo2Ie44t:-L40oxplPhTnFo2Ie44u:b-mtzhhw) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/8cd66f3b86a1b8896eab249610c3455b35cd6493/README.md#L16)):*
> ```Markdown
> * ends_in_codon & last_full_codon = equivalent of above
> ```

Could this be more idiot proof, eg explain that for each amplicon in swift_56_amplicons.txt want to find the corresponding coordinates for the canonical transcripts (as defined by clinvar) (basically what you described to me verbally)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1)*

**Comment by andyb3** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[gene_transcript_library.py, line 371 at r2](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L40nBD-fS3ZXk3_c9RW:-L41AgunPRWZmxkxaApt:b-lcr66z) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/8cd66f3b86a1b8896eab249610c3455b35cd6493/gene_transcript_library.py#L371)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

if? I can't see this being assigned anywhere
</blockquote></details>

Is assigned on line 331

---

*[gene_transcript_library.py, line 401 at r2](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L40on1TdLnnkDyERcZZ:-L41BO-ECNb8sRrqkqRJ:b-896fix) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/8cd66f3b86a1b8896eab249610c3455b35cd6493/gene_transcript_library.py#L401)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

minor issue - this should be (3)
</blockquote></details>

Done.

---

*[README.md, line 16 at r2](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-L40oxplPhTnFo2Ie44t:-L41BPA-s0yCG22h7UtR:b-896fix) ([raw file](https://github.com/moka-guys/swift56_amplicons/blob/8cd66f3b86a1b8896eab249610c3455b35cd6493/README.md#L16)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Could this be more idiot proof, eg explain that for each amplicon in swift_56_amplicons.txt want to find the corresponding coordinates for the canonical transcripts (as defined by clinvar) (basically what you described to me verbally)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/swift56_amplicons/1#-:-L41PA6pADVt9uYS8SRJ:bnfp4nl)*

**Pull request merged**
